### ISSUE TITLE
List of BAD IRB proposal traits

### ISSUE THREAD

**Issue by ZachAndrews98** [GatorEducator/IRBeast#3]
Come up with a checklist of bad IRB proposal traits for use as a checklist.

**Comment by shafferz** [comment]
We should also consider reaching out to the current Allegheny IRB chair, Rich Bowden, and find more information regarding what kinds of things hinder a proposal's ability to be successful.

**Comment by ZachAndrews98** [comment]
I see little reason to have separate issues (this issue #3 and issue #7) for good and bad item checklists, will close this issue and rename issue #7 to include both good and bad issues, as well as make a note of this change on that issue as well.
