### ISSUE TITLE
Edit the README

### ISSUE THREAD

**Issue by ZachAndrews98** [GatorEducator/IRBeast#6]
Update the readme to reflect what this tool will be used for and how to use it.

**Comment by ZachAndrews98** [comment]
We should continue to update the readme as we add in new features. We should also talk about how to install and run IRBeast including the possible commands it has.

**Comment by ZachAndrews98** [comment]
Made the first update on the readme which can be seen in PR #32. Adds sections on Installation and Running IRBeast

**Comment by Alex-Yarkosky** [comment]
Additions made in #32 are sufficient enough to close this issue.
