### ISSUE TITLE
Make a checklist of IRB proposal traits

### ISSUE THREAD

**Issue by shafferz** [GatorEducator/IRBeast#7]
We should develop a list of good traits that exist in an IRB proposal to maximize the likelihood of a successful IRB proposal submission.

**Comment by ZachAndrews98** [comment]
Changed the title to reflect the reason I closed Issue #3. There is not really a reason to have separate issues for good and bad IRB proposal traits.

**Comment by Alex-Yarkosky** [comment]
This was closed with #35
