### ISSUE TITLE
No templates for raising an issue or making a pull request

### ISSUE THREAD

**Issue by Alex-Yarkosky** [GatorEducator/IRBeast#9]
Adding these templates should be considered in order to make it easier to contribute to this as an open source project and provide uniformity. The need for these are outlined [here](https://opensource.guide/). These files are also suggested on the [Community](https://github.com/GatorEducator/IRBeast/community) page.

**Comment by Alex-Yarkosky** [comment]
It should be noted that maintainer status is needed to properly implement these kinds of templates.

**Comment by finneyj2** [comment]
Travis added
